### PR TITLE
Added support for JSON Web Encryption support (A128CBC_HS256/A256CBC_HS512)

### PR DESCRIPTION
**Pull request by rohitjoshi**
I have made following changes.
1. Added support for JWE token using alg=DIR and enc=A128CBC_HS256/A256CBC_HS512
2. Refactored code to move all string constants into a table to avoid string garbage
3. Created local aliases for the function often used
4. Added two test cases

NOTE: I ran a performance test and getting  48K JWT token creation on 2-XLarge AWS image.

### CODE REVIEW

**Comment by SkyLothar** [comment]
i need more time to go through this... sorry for keeping you waiting

**Comment by rohitjoshi** [comment]
No problem, take your time.  Let me know if you have any questions.  I did executed your existing test cases before and after merge to make sure I have not broken any existings.

One of the change I have made which could impact is _M:jwt_decode() function where reverting back special characters which were replaced in _M:jwt_encode() otherwise some of the fields from jwe keys were failing.  I did validate existing JWT login to make sure not broken.

I also moved some of the string constants to under local str_const = {} table to avoid string garbage as It is used in a high performance system. I was able to achieve 48K tps for jwt token generation through rest request on a AWS instance. E.g 

perf_access_token

**Comment by rohitjoshi** [comment]
Any updates?

**Comment by SkyLothar** [comment]
sorry for the delay.
awesome job!

but why do you include `lua resty hmac` lib?
seems like you didn't change it at all.

**Comment by rohitjoshi** [comment]
that was mistakenly committed. I have updated PR to remove that.
Thanks.

**Comment by SkyLothar** [comment]
cool! i'll release a new version in few days!

**Pull request merged**
