### PR TITLE
Review CI

### LINKED ISSUE #58: CI reports success even if tests fail
Sample CI output excerpt from https://travis-ci.org/SkyLothar/lua-resty-jwt#L224 :
```
lua-resty-jwt-tests exited with code 1

The command "docker-compose up" exited with 0.

Done. Your build exited with 0.
```

### PR DESCRIPTION
**Pull request by lucafavatella**
Closes #58.

### CODE REVIEW

**Comment by lucafavatella** [comment]
I am testing locally fix for failures.

**Comment by lucafavatella** [comment]
> I am testing locally fix for failures.

My attempt failed so do not hold your breath.

**Comment by lucafavatella** [comment]
I fixed the tests and pushed in this branch but I would need review: the syntax looked invalid (I am not a Lua expert) and after changing syntax the error string changed - not sure how relevant the specific error is. Review welcome.

**Comment by SkyLothar** [comment]
Thanks for fixing ci and tests.
Using docker-compose as test command is really a bad idea 😞

**Pull request merged**
