### PR TITLE
Openssl 1.1

### PR DESCRIPTION
**Pull request by ghost**
This change set contains two parts:
1. update vendor/resty/hmac.lua to version 0.02
2. Ensure the appropriate OpenSSL API is used. Similar to https://github.com/jkeys089/lua-resty-hmac/commit/b53f5ed964217add7e722b7c65c52b7e38a08e7f

### CODE REVIEW

**Comment by cdbattags** [comment]
Any news on when this is expected? I'm trying to use this with https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua and I'd rather not use an old version of openssl when I could just help y'all here!

Looks like https://travis-ci.org/SkyLothar/lua-resty-jwt/builds/380204655 is failing on `Socket.pm` tests at `response_body - response is expected `.

Looks like it's just a cert problem? `Cert used to sign the JWT isn't trusted: certificate has expired`

Thoughts, @cybrq-as?

Edit:

Haha all the tests are failing due to these expired certs... Lemme see what I can do.

@fermaem, I believe you were last to update these? Anything specific to know? Just go gen some new ones and we good? Last updated in April 2016.

**Comment by ghost** [comment]
Hello @cdbattags. I believe the certificate issues are fixed with https://github.com/SkyLothar/lua-resty-jwt/pull/74.

After having contacted @SkyLothar by email and not getting a reply I am wondering whether this repository is still maintained. May be someone is on vacation already... But then again, there are pull-requests from end of last year still open.

**Comment by cdbattags** [comment]
Time to fork and move on? I don't mind taking responsibility just needs a
new name for luarocks I guess...

**Comment by ghost** [comment]
Go for it. I am happy to contribute the fixes wherever they are needed. Let me know.

**Comment by miconx** [comment]
does anyone have a solution for this problem (updated package maybe?) 
ich have the problem that my keycloak installation is not working anymore because of this :-(

**Comment by fheyer** [comment]
I'm also interested in this patch. Support for OpenSSL 1.1 would be a win. I tested this patch and it works.

**Comment by cdbattags** [comment]
Hiya folks, so I've been away on vacation for Memorial Day here in the states and back tomorrow to push on this. Plan for me is to fork this repo, new name and package publish for Luarocks and then PR/notify all packages I can find that depend on this. Thoughts?

I don't have too much experience with Lua/OpenResty but I'd love to step up to the plate on this since I'll be using it across my current project on all "API gateways".

**Comment by ghost** [comment]
@cdbattags Sounds like a good plan. Let me know where I have to commit the patches to.

**Comment by cdbattags** [comment]
I had hella troubles getting the expired cert updated but since that's decently minor I went ahead and forked.

Should be getting word back on https://github.com/luarocks/luarocks-site/issues/133 any minute for my module to be added to the root manifest.

See https://github.com/cdbattags/lua-resty-jwt for latest changes. I included these specific commits (from this PR) on `v0.1.12` and skipped other current PRs until we can get the certs updated in my fork and Travis tests passing.

**Comment by ghost** [comment]
Perfect! Closing this pull-request.

**Comment by ChristianCiach** [comment]
Could you please publish to OPM? This just broke our system, because zmartzone/lua-resty-openidc depends on this package.

**Pull request closed without merging**
